### ISSUE TITLE
License

### ISSUE THREAD

**Issue by GuyLiner** [TheJakeP/NovusAgendaMigrate#1]
Hi, I'm working on a program to download the minutes from all the cities in my county and one of the cities used NovusAgenda. I wanted to ask, what license is this project under? If I were to use some some of your work I'd want to give you proper credit, etc.

**Comment by TheJakeP** [comment]
I'm never any good with licensing. I published this repo so that others could use the code. I guess I'll update it to the MIT license. It only took me a few hours to throw it all together. The hope was I could save someone a few hours of effort.

**Comment by TheJakeP** [comment]
I just updated the license

**Comment by GuyLiner** [comment]
thanks!
